# Generated by Django 5.2.8 on 2025-11-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('volume_horaire', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_professeur', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'cours',
            },
        ),
        migrations.CreateModel(
            name='HoraireCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(max_length=20)),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence_manager.cours')),
            ],
            options={
                'verbose_name': 'Horaire de Cours',
                'verbose_name_plural': 'Horaires de Cours',
                'db_table': 'horaire_cours',
            },
        ),
        migrations.CreateModel(
            name='SeanceCoure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateTimeField()),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('horaire_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence_manager.horairecours')),
            ],
            options={
                'verbose_name': 'Séance de Cours',
                'verbose_name_plural': 'Séances de Cours',
                'db_table': 'seance_coure',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etudiant', models.IntegerField()),
                ('present', models.BooleanField(default=False)),
                ('seance_coure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence_manager.seancecoure')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'presence',
            },
        ),
    ]
