# Generated by Django 5.2.8 on 2025-11-20 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('annee_academique', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_terminal', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('volume_horaire', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_professeur', models.IntegerField()),
                ('classe', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='presence_manager.classe')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'cours',
            },
        ),
        migrations.CreateModel(
            name='HoraireCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence_manager.cours')),
            ],
            options={
                'verbose_name': 'Horaire de Cours',
                'verbose_name_plural': 'Horaires de Cours',
                'db_table': 'horaire_cours',
            },
        ),
        migrations.CreateModel(
            name='SeanceCoure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('status', models.CharField(choices=[('en_cours', 'En Cours'), ('termine', 'Terminé'), ('arrete', 'Arrêté')], default='en_cours', max_length=9, verbose_name='Statut')),
                ('horaire_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence_manager.horairecours')),
            ],
            options={
                'verbose_name': 'Séance de Cours',
                'verbose_name_plural': 'Séances de Cours',
                'db_table': 'seance_coure',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etudiant', models.IntegerField()),
                ('present', models.BooleanField(default=False)),
                ('seance_coure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence_manager.seancecoure')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'presence',
            },
        ),
    ]
