# Generated by Django 5.2.8 on 2025-11-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelTable(
            name='cours',
            table='cours',
        ),
    ]
