# Generated by Django 5.2.8 on 2025-11-20 11:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code_terminal',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
