# Generated by Django 5.2.8 on 2025-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horairecours',
            name='heure_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horairecours',
            name='heure_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='seancecoure',
            name='date_seance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seancecoure',
            name='heure_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='seancecoure',
            name='heure_fin',
            field=models.TimeField(),
        ),
    ]
