# Generated by Django 5.2.8 on 2025-11-29 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(default='ukw', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='qrcodes', to='presence_manager.etudiant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['token'], name='presence_ma_token_51cb79_idx'), models.Index(fields=['expires_at'], name='presence_ma_expires_74d5c0_idx')],
            },
        ),
    ]
