# Generated by Django 5.2.8 on 2025-11-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence_manager', '0002_alter_classe_code_terminal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeanceCoure',
            new_name='SeanceCours',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='seance_coure',
            new_name='seance_cours',
        ),
    ]
