# Generated by Django 5.2.8 on 2025-11-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_manager', '0002_alter_horairecours_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seancecoure',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('termine', 'Terminé'), ('arrete', 'Arrêté')], default='en_cours', max_length=9, verbose_name='Statut'),
        ),
    ]
