# Generated by Django 5.2.8 on 2025-11-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_manager', '0002_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
